// 奇德芬芳 · 三端共享 API 客户端（框架无关）。
// transport 可插拔：H5/测试用 fetchTransport，微信小程序用 uniTransport。
// 三端把 common/data.js 的 mock 切真实接口时统一走此客户端（onLaunch 注入 baseUrl + 租户身份）。

/** @typedef {{status:number, json:any}} Resp */
/** @typedef {(method:string, url:string, opt:{headers:Record<string,string>, body?:string})=>Promise<Resp>} Transport */

function qs(obj) {
  if (!obj) return '';
  const p = Object.entries(obj).filter(([, v]) => v !== undefined && v !== null && v !== '')
    .map(([k, v]) => encodeURIComponent(k) + '=' + encodeURIComponent(String(v)));
  return p.length ? '?' + p.join('&') : '';
}
function rid() { // 幂等键：时间+随机，符合 ^[A-Za-z0-9_-]{1,128}$
  return 'idem-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 10);
}

/**
 * @param {{baseUrl:string, tenantId:number, storeId?:number, staffId?:number, roles?:string[], transport:Transport}} cfg
 */
export function createApi(cfg) {
  const base = cfg.baseUrl.replace(/\/$/, '');
  const hdr = (extra = {}) => ({
    ...(cfg.token ? { authorization: 'Bearer ' + cfg.token } : {}),
    'x-tenant-id': String(cfg.tenantId),
    ...(cfg.storeId ? { 'x-store-id': String(cfg.storeId) } : {}),
    ...(cfg.staffId ? { 'x-staff-id': String(cfg.staffId) } : {}),
    ...(cfg.roles ? { 'x-roles': cfg.roles.map(encodeURIComponent).join(',') } : {}), // 中文角色名 URL 编码：HTTP 头须 ISO-8859-1，server 侧 decodeURIComponent（仅 dev header-stub 路径用；JWT 路径服务端取 claims 忽略 x-roles）
    'content-type': 'application/json',
    ...extra,
  });
  const unwrap = (r) => { if (r.status >= 400) { const e = new Error((r.json && r.json.msg) || ('HTTP ' + r.status)); e.code = r.json && r.json.code; e.status = r.status; throw e; } return r.json && r.json.data; };

  return {
    listCustomers: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/customers' + qs(filter), { headers: hdr() })),
    getCustomer: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/customers/' + id, { headers: hdr() })),
    checkout: async (input, idempotencyKey = rid()) =>
      unwrap(await cfg.transport('POST', base + '/api/v1/cashier/checkout', { headers: hdr({ 'idempotency-key': idempotencyKey }), body: JSON.stringify(input) })),
    transfer: async (id, toStoreId, reason) =>
      unwrap(await cfg.transport('POST', base + '/api/v1/customers/' + id + '/transfer', { headers: hdr(), body: JSON.stringify({ toStoreId, reason }) })),
    listOrders: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/orders' + qs(filter), { headers: hdr() })),
    getOrder: async (orderNo) => unwrap(await cfg.transport('GET', base + '/api/v1/orders/' + orderNo, { headers: hdr() })),
    refundOrder: async (orderNo, reason, idempotencyKey = rid()) =>
      unwrap(await cfg.transport('POST', base + '/api/v1/orders/' + orderNo + '/refund', { headers: hdr({ 'idempotency-key': idempotencyKey }), body: JSON.stringify({ reason }) })),
    getWallet: async (id, opt) => unwrap(await cfg.transport('GET', base + '/api/v1/customers/' + id + '/wallet' + qs(opt), { headers: hdr() })),
    getBusinessStats: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/business' + qs(filter), { headers: hdr() })),
    getBusinessCharts: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/business-charts' + qs(filter), { headers: hdr() })),
    getCockpit: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/cockpit' + qs(filter), { headers: hdr() })),
    getGrossMargin: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/cost/gross-margin' + qs(filter), { headers: hdr() })),
    getMonthlyReport: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/reports/monthly' + qs(filter), { headers: hdr() })),
    getSatisfactionStats: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/satisfaction' + qs(filter), { headers: hdr() })),
    getFollowupStats: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/followup' + qs(filter), { headers: hdr() })),
    getRechargeReport: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/reports/recharge' + qs(filter), { headers: hdr() })),
    getMemberStats: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/members' + qs(filter), { headers: hdr() })),
    getMemberAnalysis: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/member-analysis' + qs(filter), { headers: hdr() })),
    getStaffPerf: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/staff-perf' + qs(filter), { headers: hdr() })),
    getNursingSales: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/nursing-sales' + qs(filter), { headers: hdr() })),
    getRevenueForecast: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/revenue-forecast' + qs(filter), { headers: hdr() })),
    getBom: async (itemId) => unwrap(await cfg.transport('GET', base + '/api/v1/items/' + itemId + '/bom', { headers: hdr() })),
    qcTemplates: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/qc/templates' + qs(filter), { headers: hdr() })),
    qcTemplate: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/qc/templates/' + id, { headers: hdr() })),
    qcCreateTemplate: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/qc/templates', { headers: hdr(), body: JSON.stringify(input) })),
    qcRecords: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/qc/records' + qs(filter), { headers: hdr() })),
    qcCreateRecord: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/qc/records', { headers: hdr(), body: JSON.stringify(input) })),
    qcBoard: async () => unwrap(await cfg.transport('GET', base + '/api/v1/qc/board', { headers: hdr() })),
    qaAsk: async (query, customerId) => unwrap(await cfg.transport('POST', base + '/api/v1/qa/ask', { headers: hdr(), body: JSON.stringify(customerId != null ? { query, customerId } : { query }) })),
    qaEntries: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/qa/entries' + qs(filter), { headers: hdr() })),
    qaSearch: async (q, limit) => unwrap(await cfg.transport('GET', base + '/api/v1/qa/search' + qs({ q, limit }), { headers: hdr() })),
    qaCreate: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/qa/entries', { headers: hdr(), body: JSON.stringify(input) })),
    qaUpdate: async (qaId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/qa/entries/' + qaId, { headers: hdr(), body: JSON.stringify(patch) })),
    qaRemove: async (qaId) => unwrap(await cfg.transport('POST', base + '/api/v1/qa/entries/' + qaId + '/remove', { headers: hdr() })),
    qaReview: async (qaId, reviewer) => unwrap(await cfg.transport('POST', base + '/api/v1/qa/entries/' + qaId + '/review', { headers: hdr(), body: JSON.stringify({ reviewer }) })),
    qaUnanswered: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/qa/unanswered' + qs(filter), { headers: hdr() })),
    qaSetUnanswered: async (id, status) => unwrap(await cfg.transport('PATCH', base + '/api/v1/qa/unanswered/' + id, { headers: hdr(), body: JSON.stringify({ status }) })),
    setBom: async (itemId, lines) => unwrap(await cfg.transport('POST', base + '/api/v1/items/' + itemId + '/bom', { headers: hdr(), body: JSON.stringify({ lines }) })),
    getItemSales: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/items' + qs(filter), { headers: hdr() })),
    getStoreCompare: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/by-store' + qs(filter), { headers: hdr() })),
    getFinanceSummary: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/finance/summary' + qs(filter), { headers: hdr() })),
    listFinance: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/finance' + qs(filter), { headers: hdr() })),
    createFinance: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/finance', { headers: hdr(), body: JSON.stringify(input) })),
    auditFinance: async (financeId, pass, reason) => unwrap(await cfg.transport('POST', base + '/api/v1/finance/' + financeId + '/audit', { headers: hdr(), body: JSON.stringify({ pass, reason }) })),
    removeFinance: async (financeId) => unwrap(await cfg.transport('POST', base + '/api/v1/finance/' + financeId + '/remove', { headers: hdr() })),
    getSmsSummary: async () => unwrap(await cfg.transport('GET', base + '/api/v1/sms/summary', { headers: hdr() })),
    getSmsAccount: async () => unwrap(await cfg.transport('GET', base + '/api/v1/sms/account', { headers: hdr() })),
    updateSmsAccount: async (patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/sms/account', { headers: hdr(), body: JSON.stringify(patch) })),
    rechargeSms: async (qty) => unwrap(await cfg.transport('POST', base + '/api/v1/sms/recharge', { headers: hdr(), body: JSON.stringify({ qty }) })),
    sendSms: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/sms/send', { headers: hdr(), body: JSON.stringify(input) })),
    listSmsRecords: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/sms/records' + qs(filter), { headers: hdr() })),
    getSettings: async () => unwrap(await cfg.transport('GET', base + '/api/v1/settings', { headers: hdr() })),
    saveSettings: async (group, values) => unwrap(await cfg.transport('POST', base + '/api/v1/settings', { headers: hdr(), body: JSON.stringify({ group, values }) })),
    listAppointments: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/appointments' + qs(filter), { headers: hdr() })),
    createAppointment: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/appointments', { headers: hdr(), body: JSON.stringify(input) })),
    setAppointmentStatus: async (apptId, status) => unwrap(await cfg.transport('PATCH', base + '/api/v1/appointments/' + apptId, { headers: hdr(), body: JSON.stringify({ status }) })),
    listInventory: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/inventory' + qs(filter), { headers: hdr() })),
    stockInbound: async (itemId, qty, ref) => unwrap(await cfg.transport('POST', base + '/api/v1/inventory/inbound', { headers: hdr(), body: JSON.stringify({ itemId, qty, ref }) })),
    stockOutbound: async (itemId, qty, ref) => unwrap(await cfg.transport('POST', base + '/api/v1/inventory/outbound', { headers: hdr(), body: JSON.stringify({ itemId, qty, ref }) })),
    listStockMovements: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/inventory/movements' + qs(filter), { headers: hdr() })),
    inventoryAlerts: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/inventory/alerts' + qs(filter), { headers: hdr() })),
    inventoryValuation: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/inventory/valuation' + qs(filter), { headers: hdr() })),
    listBatches: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/inventory/batches' + qs(filter), { headers: hdr() })),
    expiringBatches: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/inventory/batches/expiring' + qs(filter), { headers: hdr() })),
    batchInbound: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/inventory/batches', { headers: hdr(), body: JSON.stringify(input) })),
    batchConsume: async (id, qty) => unwrap(await cfg.transport('POST', base + '/api/v1/inventory/batches/' + id + '/consume', { headers: hdr(), body: JSON.stringify({ qty }) })),
    batchWriteoff: async (id, reason) => unwrap(await cfg.transport('POST', base + '/api/v1/inventory/batches/' + id + '/writeoff', { headers: hdr(), body: JSON.stringify({ reason }) })),
    listSuppliers: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/suppliers' + qs(filter), { headers: hdr() })),
    createSupplier: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/suppliers', { headers: hdr(), body: JSON.stringify(input) })),
    updateSupplier: async (id, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/suppliers/' + id, { headers: hdr(), body: JSON.stringify(patch) })),
    setSupplierStatus: async (id, status) => unwrap(await cfg.transport('POST', base + '/api/v1/suppliers/' + id + '/status', { headers: hdr(), body: JSON.stringify({ status }) })),
    removeSupplier: async (id) => unwrap(await cfg.transport('POST', base + '/api/v1/suppliers/' + id + '/remove', { headers: hdr() })),
    listPurchases: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/purchases' + qs(filter), { headers: hdr() })),
    createPurchase: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/purchases', { headers: hdr(), body: JSON.stringify(input) })),
    getPurchase: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/purchases/' + id, { headers: hdr() })),
    receivePurchase: async (id) => unwrap(await cfg.transport('POST', base + '/api/v1/purchases/' + id + '/receive', { headers: hdr() })),
    cancelPurchase: async (id) => unwrap(await cfg.transport('POST', base + '/api/v1/purchases/' + id + '/cancel', { headers: hdr() })),
    listStocktakes: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stocktakes' + qs(filter), { headers: hdr() })),
    createStocktake: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/stocktakes', { headers: hdr(), body: JSON.stringify(input) })),
    getStocktake: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/stocktakes/' + id, { headers: hdr() })),
    countStocktake: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/stocktakes/' + id + '/count', { headers: hdr(), body: JSON.stringify(input) })),
    commitStocktake: async (id) => unwrap(await cfg.transport('POST', base + '/api/v1/stocktakes/' + id + '/commit', { headers: hdr() })),
    listItems: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/items' + qs(filter), { headers: hdr() })),
    listBundles: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/bundles' + qs(filter), { headers: hdr() })),
    getBundle: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/bundles/' + id, { headers: hdr() })),
    createBundle: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/bundles', { headers: hdr(), body: JSON.stringify(input) })),
    updateBundle: async (id, input) => unwrap(await cfg.transport('PATCH', base + '/api/v1/bundles/' + id, { headers: hdr(), body: JSON.stringify(input) })),
    createItem: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/items', { headers: hdr(), body: JSON.stringify(input) })),
    updateItem: async (itemId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/items/' + itemId, { headers: hdr(), body: JSON.stringify(patch) })),
    getTags: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/customers/' + id + '/tags', { headers: hdr() })),
    addTag: async (id, tag) => unwrap(await cfg.transport('POST', base + '/api/v1/customers/' + id + '/tags', { headers: hdr(), body: JSON.stringify({ tag }) })),
    removeTag: async (id, tag) => unwrap(await cfg.transport('POST', base + '/api/v1/customers/' + id + '/untag', { headers: hdr(), body: JSON.stringify({ tag }) })),
    listLeads: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/leads' + qs(filter), { headers: hdr() })),
    createLead: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/leads', { headers: hdr(), body: JSON.stringify(input) })),
    claimLead: async (leadId, assignee) => unwrap(await cfg.transport('POST', base + '/api/v1/leads/' + leadId + '/claim', { headers: hdr(), body: JSON.stringify({ assignee }) })),
    convertLeadStatus: async (leadId, status) => unwrap(await cfg.transport('PATCH', base + '/api/v1/leads/' + leadId, { headers: hdr(), body: JSON.stringify({ status }) })),
    getFunnel: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/funnel' + qs(filter), { headers: hdr() })),
    listRooms: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/rooms' + qs(filter), { headers: hdr() })),
    createRoom: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/rooms', { headers: hdr(), body: JSON.stringify(input) })),
    updateRoom: async (roomId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/rooms/' + roomId, { headers: hdr(), body: JSON.stringify(patch) })),
    checkInRoom: async (roomId, customerId) => unwrap(await cfg.transport('POST', base + '/api/v1/rooms/' + roomId + '/checkin', { headers: hdr(), body: JSON.stringify({ customerId }) })),
    checkOutRoom: async (roomId) => unwrap(await cfg.transport('POST', base + '/api/v1/rooms/' + roomId + '/checkout', { headers: hdr() })),
    setRoomStatus: async (roomId, status) => unwrap(await cfg.transport('PATCH', base + '/api/v1/rooms/' + roomId, { headers: hdr(), body: JSON.stringify({ status }) })),
    removeRoom: async (roomId) => unwrap(await cfg.transport('POST', base + '/api/v1/rooms/' + roomId + '/remove', { headers: hdr() })),
    // 图片库：列图（补绝对 url 供 <image> 直接用）；上传（base64）
    mediaList: async (params) => (unwrap(await cfg.transport('GET', base + '/api/v1/media' + qs(params), { headers: hdr() })) || []).map((m) => ({ ...m, url: base + '/api/v1/media/' + m.media_id })),
    mediaUpload: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/media', { headers: hdr(), body: JSON.stringify(input) })),
    listContracts: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/contracts' + qs(filter), { headers: hdr() })),
    createContract: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/contracts', { headers: hdr(), body: JSON.stringify(input) })),
    updateContract: async (contractId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/contracts/' + contractId, { headers: hdr(), body: JSON.stringify(patch) })),
    submitContract: async (contractId) => unwrap(await cfg.transport('POST', base + '/api/v1/contracts/' + contractId + '/submit', { headers: hdr() })),
    auditContract: async (contractId, pass, reason) => unwrap(await cfg.transport('POST', base + '/api/v1/contracts/' + contractId + '/audit', { headers: hdr(), body: JSON.stringify({ pass, reason }) })),
    payContract: async (contractId, amount) => unwrap(await cfg.transport('POST', base + '/api/v1/contracts/' + contractId + '/pay', { headers: hdr(), body: JSON.stringify({ amount }) })),
    removeContract: async (contractId) => unwrap(await cfg.transport('POST', base + '/api/v1/contracts/' + contractId + '/remove', { headers: hdr() })),
    listStores: async () => unwrap(await cfg.transport('GET', base + '/api/v1/stores', { headers: hdr() })),
    createStore: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/stores', { headers: hdr(), body: JSON.stringify(input) })),
    updateStore: async (storeId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/stores/' + storeId, { headers: hdr(), body: JSON.stringify(patch) })),
    listStaff: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/staff' + qs(filter), { headers: hdr() })),
    createStaff: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/staff', { headers: hdr(), body: JSON.stringify(input) })),
    updateStaff: async (staffId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/staff/' + staffId, { headers: hdr(), body: JSON.stringify(patch) })),
    setStaffStatus: async (staffId, status) => unwrap(await cfg.transport('PATCH', base + '/api/v1/staff/' + staffId, { headers: hdr(), body: JSON.stringify({ status }) })),
    resetStaffPassword: async (staffId, newPassword) => unwrap(await cfg.transport('POST', base + '/api/v1/staff/' + staffId + '/reset-password', { headers: hdr(), body: JSON.stringify({ newPassword }) })),
    listRoles: async () => unwrap(await cfg.transport('GET', base + '/api/v1/roles', { headers: hdr() })),
    createRole: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/roles', { headers: hdr(), body: JSON.stringify(input) })),
    updateRole: async (roleId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/roles/' + roleId, { headers: hdr(), body: JSON.stringify(patch) })),
    removeRole: async (roleId) => unwrap(await cfg.transport('POST', base + '/api/v1/roles/' + roleId + '/remove', { headers: hdr() })),
    listDicts: async () => unwrap(await cfg.transport('GET', base + '/api/v1/dicts', { headers: hdr() })),
    getDict: async (code) => unwrap(await cfg.transport('GET', base + '/api/v1/dicts/' + code, { headers: hdr() })),
    getBrand: async () => unwrap(await cfg.transport('GET', base + '/api/v1/brand', { headers: hdr() })), // C端品牌/运营文案(机构名/标语/积分位)
    setDictItem: async (code, input) => unwrap(await cfg.transport('PATCH', base + '/api/v1/dicts/' + code, { headers: hdr(), body: JSON.stringify(input) })),
    listCards: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/count-cards' + qs(filter), { headers: hdr() })),
    cardValueStats: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/count-cards/value-stats' + qs(filter), { headers: hdr() })),
    issueCard: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/count-cards', { headers: hdr(), body: JSON.stringify(input) })),
    consumeCard: async (cardId, input) => unwrap(await cfg.transport('POST', base + '/api/v1/count-cards/' + cardId + '/consume', { headers: hdr(), body: JSON.stringify(input) })),
    listCardLogs: async (cardId) => unwrap(await cfg.transport('GET', base + '/api/v1/count-cards/' + cardId + '/logs', { headers: hdr() })),
    listBills: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/bills' + qs(filter), { headers: hdr() })),
    issueBill: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/bills', { headers: hdr(), body: JSON.stringify(input) })),
    payBill: async (billId, input) => unwrap(await cfg.transport('POST', base + '/api/v1/bills/' + billId + '/pay', { headers: hdr(), body: JSON.stringify(input) })),
    refundBill: async (billId, input) => unwrap(await cfg.transport('POST', base + '/api/v1/bills/' + billId + '/refund', { headers: hdr(), body: JSON.stringify(input || {}) })),
    listPayments: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/payments' + qs(filter), { headers: hdr() })),
    createPayment: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/payments', { headers: hdr(), body: JSON.stringify(input) })),
    getPayment: async (payNo) => unwrap(await cfg.transport('GET', base + '/api/v1/payments/' + payNo, { headers: hdr() })),
    sandboxPay: async (payNo) => unwrap(await cfg.transport('POST', base + '/api/v1/payments/' + payNo + '/sandbox-pay', { headers: hdr() })),
    listApprovalPending: async (bizType) => unwrap(await cfg.transport('GET', base + '/api/v1/approval/pending' + (bizType ? '?bizType=' + encodeURIComponent(bizType) : ''), { headers: hdr() })),
    listApprovals: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/approval/instances' + qs(filter), { headers: hdr() })),
    financePending: async () => unwrap(await cfg.transport('GET', base + '/api/v1/approvals', { headers: hdr() })),
    submitApproval: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/approval/submit', { headers: hdr(), body: JSON.stringify(input) })),
    approveApproval: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/approval/' + id + '/approve', { headers: hdr(), body: JSON.stringify(input) })),
    approvalRecords: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/approval/' + id + '/records', { headers: hdr() })),
    customerLifecycle: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/customers/' + id + '/lifecycle', { headers: hdr() })),
    trackingToday: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/tracking/today' + qs(filter), { headers: hdr() })),
    listRefunds: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/refunds' + qs(filter), { headers: hdr() })),
    applyRefund: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/refunds', { headers: hdr(), body: JSON.stringify(input) })),
    auditRefund: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/refunds/' + id + '/audit', { headers: hdr(), body: JSON.stringify(input) })),
    payoutRefund: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/refunds/' + id + '/payout', { headers: hdr(), body: JSON.stringify(input || {}) })),
    payChannels: async () => unwrap(await cfg.transport('GET', base + '/api/v1/pay-channels', { headers: hdr() })),
    commissionMatrix: async (storeId) => unwrap(await cfg.transport('GET', base + '/api/v1/commission-rules/matrix' + qs({ storeId }), { headers: hdr() })),
    promoRules: async () => unwrap(await cfg.transport('GET', base + '/api/v1/promo-rules', { headers: hdr() })),
    salesRewards: async () => unwrap(await cfg.transport('GET', base + '/api/v1/sales-rewards', { headers: hdr() })),
    upsertCommissionRule: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/commission-rules', { headers: hdr(), body: JSON.stringify(input) })),
    listTargets: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/targets' + qs(filter), { headers: hdr() })),
    targetProgress: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/targets/progress' + qs(filter), { headers: hdr() })),
    upsertTarget: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/targets', { headers: hdr(), body: JSON.stringify(input) })),
    nursingTemplate: async () => unwrap(await cfg.transport('GET', base + '/api/v1/nursing-assessments/template', { headers: hdr() })),
    listNursingAssessments: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/nursing-assessments' + qs(filter), { headers: hdr() })),
    createNursingAssessment: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/nursing-assessments', { headers: hdr(), body: JSON.stringify(input) })),
    nursingTimeline: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/customers/' + id + '/nursing-timeline', { headers: hdr() })),
    nursingTeamBoard: async (storeId) => unwrap(await cfg.transport('GET', base + '/api/v1/nursing-team-board' + qs({ storeId }), { headers: hdr() })),
    listExpenses: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/expenses' + qs(filter), { headers: hdr() })),
    applyExpense: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/expenses', { headers: hdr(), body: JSON.stringify(input) })),
    auditExpense: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/expenses/' + id + '/audit', { headers: hdr(), body: JSON.stringify(input) })),
    payExpense: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/expenses/' + id + '/pay', { headers: hdr(), body: JSON.stringify(input || {}) })),
    listInvoices: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/invoices' + qs(filter), { headers: hdr() })),
    createInvoice: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/invoices', { headers: hdr(), body: JSON.stringify(input) })),
    redFlushInvoice: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/invoices/' + id + '/red-flush', { headers: hdr(), body: JSON.stringify(input || {}) })),
    financeBreakdown: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/finance/breakdown' + qs(filter), { headers: hdr() })),
    reconcileGatewayVsBook: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/reconcile/gateway-vs-book' + qs(filter), { headers: hdr() })),
    reconcileExceptions: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/reconcile/exceptions' + qs(filter), { headers: hdr() })),
    logout: async () => unwrap(await cfg.transport('POST', base + '/api/v1/auth/logout', { headers: hdr() })),
    segmentFields: async () => unwrap(await cfg.transport('GET', base + '/api/v1/segments/fields', { headers: hdr() })),
    segmentPreview: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/segments/preview', { headers: hdr(), body: JSON.stringify(input) })),
    listSegments: async () => unwrap(await cfg.transport('GET', base + '/api/v1/segments', { headers: hdr() })),
    saveSegment: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/segments', { headers: hdr(), body: JSON.stringify(input) })),
    runSegment: async (id, limit) => unwrap(await cfg.transport('GET', base + '/api/v1/segments/' + id + '/run' + qs({ limit }), { headers: hdr() })),
    removeSegment: async (id) => unwrap(await cfg.transport('POST', base + '/api/v1/segments/' + id + '/remove', { headers: hdr() })),
    listPointsRules: async (storeId) => unwrap(await cfg.transport('GET', base + '/api/v1/points/rules' + qs({ storeId }), { headers: hdr() })),
    upsertPointsRule: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/points/rules', { headers: hdr(), body: JSON.stringify(input) })),
    earnPointsByRule: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/points/earn-by-rule', { headers: hdr(), body: JSON.stringify(input) })),
    createCustomer: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/customers', { headers: hdr(), body: JSON.stringify(input) })),
    updateCustomer: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/customers/' + id + '/update', { headers: hdr(), body: JSON.stringify(input) })),
    listHealthProfiles: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/health-profiles' + qs(filter), { headers: hdr() })),
    upsertHealthProfile: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/health-profiles', { headers: hdr(), body: JSON.stringify(input) })),
    customerHealth: async (id, domain) => unwrap(await cfg.transport('GET', base + '/api/v1/customers/' + id + '/health' + qs({ domain }), { headers: hdr() })),
    nannyGantt: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/nanny/gantt' + qs(filter), { headers: hdr() })),
    listDispatchRewards: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/dispatch-rewards' + qs(filter), { headers: hdr() })),
    listNannySettlements: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/nanny-settlements' + qs(filter), { headers: hdr() })),
    previewNannySettlement: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/nanny-settlements/preview' + qs(filter), { headers: hdr() })),
    settleNanny: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/nanny-settlements', { headers: hdr(), body: JSON.stringify(input) })),
    voidNannySettlement: async (id) => unwrap(await cfg.transport('POST', base + '/api/v1/nanny-settlements/' + id + '/void', { headers: hdr() })),
    addDispatchReward: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/dispatches/' + id + '/rewards', { headers: hdr(), body: JSON.stringify(input) })),
    dispatchSettlement: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/dispatches/' + id + '/settlement', { headers: hdr() })),
    listCouponTemplates: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/coupon-templates' + qs(filter), { headers: hdr() })),
    createCouponTemplate: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/coupon-templates', { headers: hdr(), body: JSON.stringify(input) })),
    issueCoupon: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/coupons/issue', { headers: hdr(), body: JSON.stringify(input) })),
    redeemCoupon: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/coupons/' + id + '/redeem', { headers: hdr(), body: JSON.stringify(input || {}) })),
    listCoupons: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/coupons' + qs(filter), { headers: hdr() })),
    listRechargeTiers: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/recharge-tiers' + qs(filter), { headers: hdr() })),
    upsertRechargeTier: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/recharge-tiers', { headers: hdr(), body: JSON.stringify(input) })),
    recharge: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/recharges', { headers: hdr(), body: JSON.stringify({ idempotencyKey: rid(), ...input }) })),
    listRecharges: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/recharges' + qs(filter), { headers: hdr() })),
    // 库存跨店调拨（借鉴#17）→ /stock-transfers（与下方 listTransfers 客户转店记录区分，二者后端不同域、不同表）
    listStockTransfers: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stock-transfers' + qs(filter), { headers: hdr() })),
    createTransfer: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/stock-transfers', { headers: hdr(), body: JSON.stringify(input) })),
    receiveTransfer: async (id) => unwrap(await cfg.transport('POST', base + '/api/v1/stock-transfers/' + id + '/receive', { headers: hdr() })),
    rejectTransfer: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/stock-transfers/' + id + '/reject', { headers: hdr(), body: JSON.stringify(input || {}) })),
    recommendRooms: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/room-bookings/recommend' + qs(filter), { headers: hdr() })),
    listRoomBookings: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/room-bookings' + qs(filter), { headers: hdr() })),
    assignRoom: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/room-bookings', { headers: hdr(), body: JSON.stringify(input) })),
    cancelRoomBooking: async (id, input) => unwrap(await cfg.transport('POST', base + '/api/v1/room-bookings/' + id + '/cancel', { headers: hdr(), body: JSON.stringify(input || {}) })),
    checkInRoomBooking: async (id) => unwrap(await cfg.transport('POST', base + '/api/v1/room-bookings/' + id + '/checkin', { headers: hdr() })),
    checkOutRoomBooking: async (id) => unwrap(await cfg.transport('POST', base + '/api/v1/room-bookings/' + id + '/checkout', { headers: hdr() })),
    refundPayment: async (payNo, input) => unwrap(await cfg.transport('POST', base + '/api/v1/payments/' + payNo + '/refund', { headers: hdr(), body: JSON.stringify(input || {}) })),
    listBabies: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/babies' + qs(filter), { headers: hdr() })),
    createBaby: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/babies', { headers: hdr(), body: JSON.stringify(input) })),
    addBabyLog: async (babyId, input) => unwrap(await cfg.transport('POST', base + '/api/v1/babies/' + babyId + '/logs', { headers: hdr(), body: JSON.stringify(input) })),
    babyTimeline: async (babyId, filter) => unwrap(await cfg.transport('GET', base + '/api/v1/babies/' + babyId + '/timeline' + qs(filter), { headers: hdr() })),
    listTodayDeliveries: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/catering-delivery/today' + qs(filter), { headers: hdr() })),
    markDelivered: async (planId) => unwrap(await cfg.transport('POST', base + '/api/v1/catering-delivery/' + planId + '/mark', { headers: hdr() })),
    listDeliveryHistory: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/catering-delivery/history' + qs(filter), { headers: hdr() })),
    listMealPlans: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/meal-plans' + qs(filter), { headers: hdr() })),
    createMealPlan: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/meal-plans', { headers: hdr(), body: JSON.stringify(input) })),
    listMealPlanItems: async (planId) => unwrap(await cfg.transport('GET', base + '/api/v1/meal-plans/' + planId + '/items', { headers: hdr() })),
    addMealPlanItem: async (planId, input) => unwrap(await cfg.transport('POST', base + '/api/v1/meal-plans/' + planId + '/items', { headers: hdr(), body: JSON.stringify(input) })),
    generateMealPlan: async (planId, input) => unwrap(await cfg.transport('POST', base + '/api/v1/meal-plans/' + planId + '/generate', { headers: hdr(), body: JSON.stringify(input) })),
    listMealDishes: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/meal-dishes' + qs(filter), { headers: hdr() })),
    createMealDish: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/meal-dishes', { headers: hdr(), body: JSON.stringify(input) })),
    listScripts: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/scripts' + qs(filter), { headers: hdr() })),
    createScript: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/scripts', { headers: hdr(), body: JSON.stringify(input) })),
    updateScript: async (scriptId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/scripts/' + scriptId, { headers: hdr(), body: JSON.stringify(patch) })),
    removeScript: async (scriptId) => unwrap(await cfg.transport('POST', base + '/api/v1/scripts/' + scriptId + '/remove', { headers: hdr() })),
    pushNotice: async (id, type, title) => unwrap(await cfg.transport('POST', base + '/api/v1/customers/' + id + '/notices', { headers: hdr(), body: JSON.stringify({ type, title }) })),
    listNotices: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/customers/' + id + '/notices', { headers: hdr() })),
    markNoticeRead: async (noticeId) => unwrap(await cfg.transport('POST', base + '/api/v1/notices/' + noticeId + '/read', { headers: hdr() })),
    getNursingStats: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/stats/nursing' + qs(filter), { headers: hdr() })),
    listNursing: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/nursing' + qs(filter), { headers: hdr() })),
    nursingCareAlerts: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/nursing/care-alerts' + qs(filter), { headers: hdr() })),
    createNursing: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/nursing', { headers: hdr(), body: JSON.stringify(input) })),
    setNursingStatus: async (serviceId, status) => unwrap(await cfg.transport('PATCH', base + '/api/v1/nursing/' + serviceId, { headers: hdr(), body: JSON.stringify({ status }) })),
    listHandovers: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/handovers' + qs(filter), { headers: hdr() })),
    createHandover: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/handovers', { headers: hdr(), body: JSON.stringify(input) })),
    confirmHandover: async (handoverId) => unwrap(await cfg.transport('POST', base + '/api/v1/handovers/' + handoverId + '/confirm', { headers: hdr() })),
    listSchedules: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/schedules' + qs(filter), { headers: hdr() })),
    createSchedule: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/schedules', { headers: hdr(), body: JSON.stringify(input) })),
    updateSchedule: async (scheduleId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/schedules/' + scheduleId, { headers: hdr(), body: JSON.stringify(patch) })),
    removeSchedule: async (scheduleId) => unwrap(await cfg.transport('POST', base + '/api/v1/schedules/' + scheduleId + '/remove', { headers: hdr() })),
    getTimeline: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/customers/' + id + '/timeline', { headers: hdr() })),
    listTransfers: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/transfers' + qs(filter), { headers: hdr() })),
    getNutritionStats: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/diet/stats' + qs(filter), { headers: hdr() })),
    listDiet: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/diet' + qs(filter), { headers: hdr() })),
    createDiet: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/diet', { headers: hdr(), body: JSON.stringify(input) })),
    updateDiet: async (planId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/diet/' + planId, { headers: hdr(), body: JSON.stringify(patch) })),
    removeDiet: async (planId) => unwrap(await cfg.transport('POST', base + '/api/v1/diet/' + planId + '/remove', { headers: hdr() })),
    listProducts: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/products' + qs(filter), { headers: hdr() })),
    createProduct: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/products', { headers: hdr(), body: JSON.stringify(input) })),
    updateProduct: async (productId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/products/' + productId, { headers: hdr(), body: JSON.stringify(patch) })),
    mallPurchase: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/mall/purchase', { headers: hdr(), body: JSON.stringify(input) })),
    getPoints: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/customers/' + id + '/points', { headers: hdr() })),
    listPointLedger: async (id) => unwrap(await cfg.transport('GET', base + '/api/v1/customers/' + id + '/points/ledger', { headers: hdr() })),
    earnPoints: async (id, amount, reason) => unwrap(await cfg.transport('POST', base + '/api/v1/customers/' + id + '/points/earn', { headers: hdr(), body: JSON.stringify({ amount, reason }) })),
    redeemPoints: async (id, amount, reason) => unwrap(await cfg.transport('POST', base + '/api/v1/customers/' + id + '/points/redeem', { headers: hdr(), body: JSON.stringify({ amount, reason }) })),
    listPosts: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/posts' + qs(filter), { headers: hdr() })),
    createPost: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/posts', { headers: hdr(), body: JSON.stringify(input) })),
    updatePost: async (postId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/posts/' + postId, { headers: hdr(), body: JSON.stringify(patch) })),
    likePost: async (postId) => unwrap(await cfg.transport('POST', base + '/api/v1/posts/' + postId + '/like', { headers: hdr() })),
    removePost: async (postId) => unwrap(await cfg.transport('POST', base + '/api/v1/posts/' + postId + '/remove', { headers: hdr() })),
    listMallOrders: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/mall/orders' + qs(filter), { headers: hdr() })),
    listOpsRecords: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/ops/records' + qs(filter), { headers: hdr() })),
    createOpsRecord: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/ops/records', { headers: hdr(), body: JSON.stringify(input) })),
    updateOpsRecord: async (recordId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/ops/records/' + recordId, { headers: hdr(), body: JSON.stringify(patch) })),
    listNannies: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/nannies' + qs(filter), { headers: hdr() })),
    createNanny: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/nannies', { headers: hdr(), body: JSON.stringify(input) })),
    updateNanny: async (nannyId, patch) => unwrap(await cfg.transport('PATCH', base + '/api/v1/nannies/' + nannyId, { headers: hdr(), body: JSON.stringify(patch) })),
    listDispatch: async (filter) => unwrap(await cfg.transport('GET', base + '/api/v1/nanny-dispatch' + qs(filter), { headers: hdr() })),
    createDispatch: async (input) => unwrap(await cfg.transport('POST', base + '/api/v1/nanny-dispatch', { headers: hdr(), body: JSON.stringify(input) })),
    auditDispatch: async (dispatchId, pass, reason) => unwrap(await cfg.transport('POST', base + '/api/v1/nanny-dispatch/' + dispatchId + '/audit', { headers: hdr(), body: JSON.stringify({ pass, reason }) })),
    checkinDispatch: async (dispatchId) => unwrap(await cfg.transport('POST', base + '/api/v1/nanny-dispatch/' + dispatchId + '/checkin', { headers: hdr() })),
    completeDispatch: async (dispatchId) => unwrap(await cfg.transport('POST', base + '/api/v1/nanny-dispatch/' + dispatchId + '/complete', { headers: hdr() })),
    removeDispatch: async (dispatchId) => unwrap(await cfg.transport('POST', base + '/api/v1/nanny-dispatch/' + dispatchId + '/remove', { headers: hdr() })),
    login: async (phone, password) => unwrap(await cfg.transport('POST', base + '/api/v1/auth/login', { headers: hdr(), body: JSON.stringify({ phone, password }) })),
    loginCustomer: async (customerId) => unwrap(await cfg.transport('POST', base + '/api/v1/auth/login-customer', { headers: hdr(), body: JSON.stringify({ customerId }) })),
    demoAccounts: async () => unwrap(await cfg.transport('GET', base + '/api/v1/auth/demo-accounts', { headers: hdr() })),
    _raw: cfg.transport, // 需要原始 {status,json} 时
  };
}

/** H5 / 测试：基于全局 fetch（15s 超时，弱网/挂起自动中止 → 上层 catch 提示重试）。 */
export const fetchTransport = async (method, url, opt) => {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 15000);
  try {
    const r = await fetch(url, { method, headers: opt.headers, body: opt.body, signal: ctrl.signal });
    let json = null; try { json = await r.json(); } catch { /* 非 JSON */ }
    return { status: r.status, json };
  } finally { clearTimeout(timer); }
};

/** 微信小程序：基于 uni.request（mp 运行时全局 uni；15s 超时）。 */
export const uniTransport = (method, url, opt) => new Promise((resolve, reject) => {
  // eslint-disable-next-line no-undef
  uni.request({
    url, method, header: opt.headers, data: opt.body ? JSON.parse(opt.body) : undefined, timeout: 15000,
    success: (res) => resolve({ status: res.statusCode, json: res.data }),
    fail: reject,
  });
});
