-- MySQL 5.7
-- Complete employee roster fields. The project owner explicitly requires
-- plaintext display/storage for phone numbers and other roster PII.

ALTER TABLE staff
  MODIFY phone VARCHAR(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  ADD COLUMN age_at_source SMALLINT DEFAULT NULL AFTER gender,
  ADD COLUMN tenure_text VARCHAR(64) DEFAULT NULL AFTER employment_status,
  ADD COLUMN promotion_history TEXT DEFAULT NULL AFTER tenure_text,
  ADD COLUMN contract_years_text VARCHAR(32) DEFAULT NULL AFTER promotion_history,
  ADD COLUMN contract_start_date DATE DEFAULT NULL AFTER contract_years_text,
  ADD COLUMN contract_end_date DATE DEFAULT NULL AFTER contract_start_date,
  ADD COLUMN contract_expiry_reminder VARCHAR(32) DEFAULT NULL AFTER contract_end_date,
  ADD COLUMN contract_sign_count INT DEFAULT NULL AFTER contract_expiry_reminder,
  ADD COLUMN source_status VARCHAR(32) DEFAULT NULL AFTER contract_sign_count,
  ADD COLUMN source_note TEXT DEFAULT NULL AFTER source_status;

ALTER TABLE staff_private
  DROP INDEX uk_staff_private_mobile_hash,
  DROP INDEX uk_staff_private_id_hash,
  DROP COLUMN encryption_version,
  DROP COLUMN mobile_cipher,
  DROP COLUMN mobile_hash,
  DROP COLUMN id_no_cipher,
  DROP COLUMN id_no_hash,
  DROP COLUMN home_address_cipher,
  DROP COLUMN emergency_name_cipher,
  DROP COLUMN emergency_phone_cipher,
  ADD COLUMN id_no VARCHAR(32) DEFAULT NULL AFTER staff_id,
  ADD COLUMN id_no_raw VARCHAR(128) DEFAULT NULL AFTER id_no,
  ADD COLUMN id_no_valid TINYINT(1) NOT NULL DEFAULT 0 AFTER id_no_raw,
  ADD COLUMN id_valid_until DATE DEFAULT NULL AFTER id_no_valid,
  ADD COLUMN home_address VARCHAR(1024) DEFAULT NULL AFTER id_valid_until,
  ADD COLUMN emergency_contact_name VARCHAR(64) DEFAULT NULL AFTER home_address,
  ADD COLUMN emergency_contact_phone VARCHAR(32) DEFAULT NULL AFTER emergency_contact_name,
  ADD COLUMN salary_card_no VARCHAR(64) DEFAULT NULL AFTER emergency_contact_phone,
  ADD KEY ix_staff_private_id_no (id_no),
  ADD KEY ix_staff_private_emergency_phone (emergency_contact_phone);

CREATE TABLE IF NOT EXISTS staff_roster_records (
  roster_record_id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  staff_id BIGINT DEFAULT NULL,
  employee_no VARCHAR(32) DEFAULT NULL,
  staging_no VARCHAR(32) DEFAULT NULL,
  source_file VARCHAR(255) NOT NULL,
  source_page INT NOT NULL,
  source_seq INT DEFAULT NULL,
  source_row_order INT NOT NULL,
  department VARCHAR(128) DEFAULT NULL,
  position VARCHAR(128) DEFAULT NULL,
  employee_name VARCHAR(64) NOT NULL,
  gender VARCHAR(8) DEFAULT NULL,
  age_at_source SMALLINT DEFAULT NULL,
  education VARCHAR(32) DEFAULT NULL,
  mobile VARCHAR(32) DEFAULT NULL,
  id_no VARCHAR(32) DEFAULT NULL,
  id_no_raw VARCHAR(128) DEFAULT NULL,
  id_no_valid TINYINT(1) NOT NULL DEFAULT 0,
  birth_date DATE DEFAULT NULL,
  id_valid_until DATE DEFAULT NULL,
  home_address VARCHAR(1024) DEFAULT NULL,
  emergency_contact_name VARCHAR(64) DEFAULT NULL,
  emergency_contact_phone VARCHAR(32) DEFAULT NULL,
  hire_date DATE DEFAULT NULL,
  tenure_text VARCHAR(64) DEFAULT NULL,
  promotion_history TEXT DEFAULT NULL,
  contract_years_text VARCHAR(32) DEFAULT NULL,
  contract_start_date DATE DEFAULT NULL,
  contract_end_date DATE DEFAULT NULL,
  contract_expiry_reminder VARCHAR(32) DEFAULT NULL,
  contract_sign_count INT DEFAULT NULL,
  salary_card_no VARCHAR(64) DEFAULT NULL,
  employment_status VARCHAR(20) NOT NULL,
  source_status VARCHAR(32) DEFAULT NULL,
  source_note TEXT DEFAULT NULL,
  review_status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (roster_record_id),
  KEY ix_roster_store_status (tenant_id, store_id, employment_status),
  KEY ix_roster_staff (staff_id),
  KEY ix_roster_mobile (mobile),
  KEY ix_roster_id_no (id_no),
  KEY ix_roster_source (source_file(64), source_page, source_row_order),
  CONSTRAINT fk_roster_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id),
  CONSTRAINT fk_roster_store
    FOREIGN KEY (store_id) REFERENCES stores (store_id),
  CONSTRAINT fk_roster_staff
    FOREIGN KEY (staff_id) REFERENCES staff (staff_id)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
